Feature/activity import command
reload/ddsdk2016 pull request #355
Opened 2020-09-09 08:22 UTC by spaceo

#### What does this PR do?

#### Where should the reviewer start?

#### How should this be manually tested?

#### Any background context you want to provide?

#### What are the relevant tickets?

#### Screenshots (if appropriate)

#### Questions for the reviewer:

2020-09-11 14:18 UTC, xendk approved these changes

2020-09-15 13:22 UTC, arnested requested changes
Generelt godt og flot! Og gør hvad det skal, ikke mindst.

Jeg har lidt stilistiske kommentarer til PR'et.

Og så har mit falkeøje spottet nogle visuelle ting:

*  Teasere kan have noget markup (https://pr-355-m5kibzq-55isd6w54kg6s.eu.platform.sh/aktiviteter/primitiv-baltaending):
<img width="918" alt="teaser" src="https://user-images.githubusercontent.com/190005/93215152-526fb980-f766-11ea-914d-90a4a7f971e9.png">

* I søgeresultater ser det ud som om varighed står efter labelen mens de to andre står under labelen:
<img width="750" alt="search" src="https://user-images.githubusercontent.com/190005/93215487-c611c680-f766-11ea-8a04-f7dc8d30b5b5.png">

* Det ser lidt spøjst ud når galleri som den eneste label / mellemrubrik har et kolon på:
<img width="323" alt="Untitled" src="https://user-images.githubusercontent.com/190005/93215807-34568900-f767-11ea-8c1e-cc993c45600e.png">

2020-09-15 13:22 UTC, arnested commented on web/themes/custom/mungo/mungo.theme
> +  // TODO: Move this list of displays to a centralized place.
TODO? Er det noget vi bør gøre med det samme?

Min erfaring med TODO's i kode er at ingen forholder sig til dem. Så enten bør det fixes nu man er i gang eller også skal man oprette en Jira-ticket på det så det aktivt kan prioriteres at/om ændre det.

Nå, det er en kæphest jeg kan tale længe om :)

2020-09-15 15:44 UTC, xendk commented on web/themes/custom/mungo/mungo.theme
> +  // TODO: Move this list of displays to a centralized place.
Eller lav en Fini og omformuler det til // This should be....

Min erfaring er at tekniske TODOs oprettede som tickets ryger i bunden af backloggen og så tilbringer resten af deres tilværelse der.

Men en note om hvad der var tænkt har en chance for at blive effektureret når nogen refatorerer deromkring (og ticket'en er der ingen der husker).

2020-09-15 15:48 UTC, xendk commented on web/modules/custom/dds_activity/src/ActivityFetcher.php
> +
Ikke bare dig, også PHPCS Drupal/DrupalPractice coding standard.

2020-09-15 15:49 UTC, xendk commented on web/modules/custom/dds_activity/src/ActivityFetcher.php
> +
...ihvertfald i mit lokale setup?

2020-09-16 06:38 UTC, spaceo commented on composer.json
> +        "mglaman/phpstan-drupal": "^0.12.5",
Ok. Fjerner den igen. :)

2020-09-16 07:06 UTC, spaceo commented on web/modules/custom/dds_activity/src/ActivityFetcher.php
> +//            watchdog_exception('dds_activity', $e);
Yeah. Det var en del af Mads kode som jeg havde mod på at fjerne helt. Men det larmer sindsygt meget i drush context når der er en activity id der ikke findes. Jeg fjerner det.

2020-09-16 07:16 UTC, spaceo commented on web/themes/custom/mungo/mungo.theme
> +  // TODO: Move this list of displays to a centralized place.
@arnested @xendk Er enig Fini's holdning ifht sovende tickets i backlog. I min verden er en TODO noget der ikke er strengt nødvendigt, men ville være rart at få fikset når man nu alligevel er i gang med det område af koden - f.eks. i en refaktorering.

2020-09-16 07:59 UTC, xendk commented on web/themes/custom/mungo/mungo.theme
> +  // TODO: Move this list of displays to a centralized place.
Men det skal også siges at en `// TODO:` skærer mig lige så meget i øjnene som det gør Arne. Det føles ligesom noget der *skal* gøres. Grunden til den syntax er jo netop for at man kan greppe sig frem til "ting der skal gøres". Derfor jeg laver dem som noter uden `TODO`.

2020-09-16 08:41 UTC, spaceo commented
@arnested Har fixet alt hvad der ikke havde at gøre med code style, da jeg tager den del i branchen der sletter skidtet igen.

2020-09-16 09:30 UTC, arnested approved these changes
LGTM :+1:

2020-10-19 08:53 UTC, merged