DG-270: Show spejder.dk in node teaser
reload/ddsdk2016 pull request #407
Opened 2022-03-28 14:55 UTC by mikkelblyme

- Add cert volume to fpm container
- DG-270: Show 'spejder.dk' in node teaser

#### What does this PR do?

#### Where should the reviewer start?

#### How should this be manually tested?

#### Any background context you want to provide?

#### What are the relevant tickets?

#### Screenshots (if appropriate)

#### Questions for the reviewer:

2022-03-29 09:43 UTC, arnested requested changes
To kommentarer (eller den samme to steder) i koden.

Desuden: når der er to tags bør vi så smide en dot eller tankestreg i mellem for at skille dem tydeligere end med spacing?

2022-03-29 09:43 UTC, arnested commented on web/themes/custom/mungo/templates/content/node--extended-teaser.html.twig
> +                  <li>{{ content.field_content_topic }}</li>
Det bliver skævt det her hvis der er en spejderdk_target_group, men ikke en field_content_typic ... så får man en tom <li>

2022-03-29 09:43 UTC, arnested commented on web/themes/custom/mungo/templates/content/node--teaser.html.twig
> +                <li>{{ content.field_content_topic }}</li>
Samme som den anden kommentar.

2022-03-29 10:59 UTC, mikkelblyme commented on web/themes/custom/mungo/templates/content/node--extended-teaser.html.twig
> +                  <li>{{ content.field_content_topic }}</li>
Jeg har rettet til i mit seneste commit 👍 
`field_content_topic` er required på noden
<img width="348" alt="image" src="https://user-images.githubusercontent.com/68547893/160585044-647cca4f-4f03-40bd-8c89-9dddb99a3f91.png">

2022-03-29 12:28 UTC, arnested approved these changes
LGTM :+1:

2022-05-20 10:05 UTC, arnested commented
Nu hvor navnet er valgt til at være Track kunne det være man skulle bruge det i steder for spejder.dk i koden?

2022-05-20 11:30 UTC, mikkelblyme commented
backstop-check approve

2022-05-20 11:31 UTC, merged