Track
reload/ddsdk2016 pull request #417
Opened 2022-05-30 08:44 UTC by mikkelblyme

#### What does this PR do?

#### Where should the reviewer start?

#### How should this be manually tested?

#### Any background context you want to provide?

#### What are the relevant tickets?

#### Screenshots (if appropriate)

#### Questions for the reviewer:

2022-06-24 12:07 UTC, rasben requested changes
Looks good :) A couple of findings, but nothing major.

P.S. I dont see any translation updates? (da.po / add_translation())

2022-06-24 12:07 UTC, rasben commented on web/themes/custom/mungo/assets_src/sass/track/_section-page.scss
> +      // @include header-with-bg(subtitle)
Looks like a mistake.

2022-06-24 12:07 UTC, rasben commented on web/themes/custom/mungo/assets_src/sass/track/_section-page.scss
> +      @if ($track != "arrangementer") {
It is a bit ugly to use a danish word in the CSS, but i assume you have no choice in terms of using a TID instead?

2022-06-24 12:07 UTC, rasben commented on web/themes/custom/mungo/mungo.theme
>      $paragraph = $variables['element']['#object'];
I really think using instance of + return would be more stable here.

2022-06-24 12:07 UTC, rasben commented on web/themes/custom/mungo/mungo.theme
> +      $node = \Drupal::routeMatch()->getParameter('node');
See my comments earlier about `instance of`

2022-06-24 12:07 UTC, rasben commented on web/themes/custom/mungo/mungo.theme
> +  $node = \Drupal::routeMatch()->getParameter('node');
See my comments earlier about `instance of`

2022-06-24 12:07 UTC, rasben commented on web/themes/custom/mungo/templates/paragraphs/paragraph--embed.html.twig
> +          dette indhold</a>
missing translation

2022-06-24 12:32 UTC, mikkelblyme commented on configuration/drupal/field.storage.paragraph.field_situation_color.yml
> +      label: 'Track - skills (purple)'
Good call. Retter til dansk

2022-06-24 12:50 UTC, mikkelblyme commented on web/sites/default/docker.settings.php
> +# $settings['cache']['bins']['render'] = 'cache.backend.null';
No, on purpose. We mimic prod by default

2022-06-24 13:15 UTC, mikkelblyme commented on configuration/drupal/core.entity_form_display.node.event.default.yml
> -        label: 'Event presentation'
https://github.com/reload/ddsdk2016/blob/master/configuration/drupal/core.entity_form_display.node.event.default.yml#L66

2022-06-27 07:20 UTC, rasben approved these changes

2022-06-27 07:30 UTC, mikkelblyme commented
backstop-check approve

2022-06-27 07:31 UTC, merged